SurveyTool/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SurveyTool.Models;

namespace SurveyTool.Controllers
{
    [Authorize]
    public class ReportsController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ReportsController(ApplicationDbContext db)
        {
            _db = db;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var surveys = _db.Surveys.Where(x => x.UserId.Equals(userId)).ToList();
            return View(surveys);
        }

        [HttpGet]
        public ActionResult Details(int id, int? departmentId, DateTime? startDate, DateTime? endDate)
        {
            var questions = new List<QuestionViewModel>();
            startDate = startDate ?? new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1);
            endDate = endDate ?? DateTime.Now;

            var survey = _db.Surveys.Single(s => s.Id == id);

            _db.Questions
               .Where(q => q.SurveyId == id)
               .OrderBy(q => q.Priority)
               .Select(q => new
                   {
                       q.Title,
                       q.Body,
                       q.Type,
                       Answers = _db.Answers.Where(a => a.QuestionId == q.Id &&
                                                        a.Response.CreatedOn >= startDate.Value &&
                                                        a.Response.CreatedOn <= endDate.Value)
                   })
               .ToList()
               .ForEach(r => questions.Add(new QuestionViewModel
                   {
                       Title = r.Title,
                       Body = r.Body,
                       Type = r.Type,
                       Answers = r.Answers.ToList()
                   }));

            var vm = new ReportViewModel
                {
                    StartDate = startDate.Value,
                    EndDate = endDate.Value,
                    Survey = survey,
                    Responses = questions
                };

            return View(vm);
        }
    }
}

SurveyTool/Controllers/SurveysController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.AspNet.Identity;
using SurveyTool.Models;
using SurveyTool.Models.ViewModel;

namespace SurveyTool.Controllers
{
    [Authorize]
    public class SurveysController : Controller
    {
        private readonly ApplicationDbContext _db;

        public SurveysController(ApplicationDbContext db)
        {
            _db = db;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var surveys = _db.Surveys.Where(x => x.UserId.Equals(userId)).ToList();
            return View(surveys);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var survey = new Survey
            {
                StartDate = DateTime.Now,
                EndDate = DateTime.Now.AddYears(1)
            };
            var userId = User.Identity.GetUserId();
            survey.UserId = userId;
            return View(survey);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Survey survey, string action)
        {
            int i = 1;
            var userId = User.Identity.GetUserId();
            survey.UserId = userId;
            //create question email if required email
            if(survey.RequiredEmail)
            {
                var ques = new Question();
                ques.IsActive = true;
                ques.Required = true;
                ques.Type = "Email";
                ques.Priority = 0;
                ques.Title = "Thu thập email người dùng";
                ques.Body = "Nhập email của bạn";
                ques.SurveyId = survey.Id;
                survey.Questions.Add(ques);
                foreach (var item in survey.Questions)
                {
                    if(!item.Type.Equals("Email"))
                    {
                        item.Priority = i;
                        i++;
                    }
                    else
                    {
                        continue;
                    }
                }
            }

            //var errors = ModelState
            //    .Where(x => x.Value.Errors.Count > 0)
            //    .Select(x => new { x.Key, x.Value.Errors })
            //    .ToArray();

            //cập nhật thời gian tạo và thay đổi = thời gian hiện tại
            survey.Questions.ForEach(q => q.CreatedOn = q.ModifiedOn = DateTime.Now);

            _db.Surveys.Add(survey);
            _db.SaveChanges();
            TempData["success"] = "Khảo sát đã được tạo thành công!";
            return RedirectToAction("Edit", new { id = survey.Id });
            //}
            //else
            //{
            //    TempData["error"] = "Đã có lỗi xảy ra trong quá trình tạo";
            //    return View(survey);
            //}
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var survey = _db.Surveys.Include("Questions").Single(x => x.Id == id);
            survey.Questions = survey.Questions.OrderBy(q => q.Priority).ToList();
            var userId = User.Identity.GetUserId();
            survey.UserId = userId;
            return View(survey);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Survey model)
        {
            var userId = User.Identity.GetUserId();
            model.UserId = userId;
            foreach (var question in model.Questions)
            {
                question.SurveyId = model.Id;

                if(question.Type.Equals("Email"))
                {
                    if(model.RequiredEmail)
                    {
                        question.Required = true;
                    }
                    else
                    {
                        question.Required = false;
                    }
                }

                if (question.Id == 0)
                {
                    question.CreatedOn = DateTime.Now;
                    question.ModifiedOn = DateTime.Now;
                    _db.Entry(question).State = EntityState.Added;
                }
                else
                {
                    question.ModifiedOn = DateTime.Now;
                    _db.Entry(question).State = EntityState.Modified;
                    _db.Entry(question).Property(x => x.CreatedOn).IsModified = false;
                }
            }

            _db.Entry(model).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Edit", new { id = model.Id });
        }

        [HttpPost]
        public ActionResult Delete(Survey survey)
        {
            _db.Entry(survey).State = EntityState.Deleted;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

SurveyTool/Views/Shared/_CustomerLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - Khảo sát</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/cleditor")
    @Styles.Render("~/Content/toastr")
    @Styles.Render("~/Content/site")
</head>
<body>
    <div id="content" class="container">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/knockout")
    @Scripts.Render("~/bundles/toastr")
    @RenderSection("scripts", required: false)
    @Html.Partial("_FlashPartial")
</body>
</html>

SurveyTool/Views/Shared/_FlashPartial.cshtml
@foreach (var key in TempData.Keys)
{
    <script type="text/javascript">
        $(function() {
            toastr["@(key)"]("@TempData[key]");
        });
    </script>
}

SurveyTool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - Khảo sát</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/cleditor")
    @Styles.Render("~/Content/toastr")
    @Styles.Render("~/Content/site")
    @Scripts.Render("~/bundles/jquery")
    <link href="~/Assets/css/email.multiple.css" rel="stylesheet" />
    <style>
        .popupSocial {
            z-index: 999;
            text-align: center;
            background: #2c4584;
            position: fixed;
            top: 45%;
            left: 10px;
            padding: 20px 10px;
            border: 1px solid #333;
            border-radius: 10px;
        }

        media screen and (max-width:768px) {
            .popupSocial

        {
            display: none;
        }
    </style>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="brand" href="/">Web Survey</a>
                @Html.Partial("_MenuPartial")
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div id="content" class="container">
        @RenderBody()
    </div>
    @*<div id="fb-root"></div>
    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.8&appId=966085800437135";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
    <div class="popupSocial">
        <div class="fb-like" data-href="https://www.facebook.com/Web-Survey-UET-101692197977054/" data-layout="box_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
        <br /><br />
        <div style="width:60px">
            <script src="https://apis.google.com/js/platform.js" async defer></script>
            <g:plusone></g:plusone>
        </div>
    </div>*@

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/knockout")
    @Scripts.Render("~/bundles/toastr")
    @RenderSection("scripts", required: false)
    @Html.Partial("_FlashPartial")
</body>
</html>

SurveyTool/Views/Shared/_MenuPartial.cshtml
@if (Request.IsAuthenticated)
{
    <ul class="nav">
        <li><a href="/Dashboard/Index">Trang chủ</a></li>
        <li><a href="@Url.Action("Index", "Statistic")">Thống kê</a></li>
        <li><a href="@Url.Action("Index", "Surveys")">Quản lý khảo sát</a></li>
        @if (User.IsInRole("Admin"))
        {
            @*<li><a href="@Url.Action("Index", "Reports")">Phản hồi</a></li>*@
            <li><a href="@Url.Action("Index", "ManageUser")">Quản lý thành viên</a></li>
        }
    </ul>
}