SurveyTool/Controllers/SurveyCustomerController.cs
using SurveyTool.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SurveyTool.Controllers
{
    public class SurveyCustomerController : Controller
    {
        private readonly ApplicationDbContext _db;
        public SurveyCustomerController(ApplicationDbContext db)
        {
            this._db = db;
        }

        [HttpGet]
        public ActionResult Create(int surveyId)
        {
            var survey = _db.Surveys
                            .Where(s => s.Id == surveyId)
                            .Select(s => new
                            {
                                Survey = s,
                                Questions = s.Questions
                                                 .Where(q => q.IsActive)
                                                 .OrderBy(q => q.Priority)
                            })
                             .AsEnumerable()
                             .Select(x =>
                             {
                                 x.Survey.Questions = x.Questions.ToList();
                                 return x.Survey;
                             })
                             .Single();
            
            return View(survey);
        }

        [HttpPost]
        public ActionResult CreateResponse(int surveyId, string action, Response model)
        {
            if (Session["customer"] == null)
            {
                CustomerSession customerSession = new CustomerSession();
                customerSession.NameIp = GetIp();
                customerSession.TotalSurvey = 1;
                customerSession.TotalSurvey -= 1;
                Session["customer"] = customerSession;
            }
            else
            {
                CustomerSession cus = (CustomerSession)Session["customer"];
                if (cus.NameIp == GetIp() && cus.TotalSurvey <= 0)
                {
                    return RedirectToAction("NotSubmitSurvey");
                }
                cus.TotalSurvey -= 1;
                Session["customer"] = cus;
            }
            bool checkInvalidEmail = false;

            model.Answers = model.Answers.Where(a => !String.IsNullOrEmpty(a.Value)).ToList();
            model.SurveyId = surveyId;
            model.CreatedOn = DateTime.Now;
            //Save infomation customer response
            var customer = new Customer();
            foreach (var item in model.Answers)
            {
                var question = _db.Questions.Where(x => x.Id == item.QuestionId).FirstOrDefault();
                if (question.Type.Equals("Email"))
                {
                    customer.Email = item.Value;
                    customer.Name = item.Value;
                    model.CreatedBy = item.Value;
                    checkInvalidEmail = true;
                }
            }
            if(checkInvalidEmail==false)
            {
                model.CreatedBy = "Khách vãng lai";

            }
            _db.Customers.Add(customer);
            _db.SaveChanges();

            model.CusId = customer.Id;
            _db.Responses.Add(model);
            _db.SaveChanges();
            return RedirectToAction("PageResponse",new {surveyId});
        }
        public ActionResult PageResponse(int surveyId)
        {
            ViewBag.SurveyId = surveyId;
            return View();
        }
        public ActionResult NotSubmitSurvey()
        {
            return View();
        }
        public string GetIp()
        {
            IPHostEntry host;
            string localIP = "?";
            host = Dns.GetHostEntry(Dns.GetHostName());
            foreach (var ip in host.AddressList)
            {
                if (ip.AddressFamily.ToString() == "InterNetwork")
                {
                    localIP = ip.ToString();
                }
            }
            return localIP;
        }
    }
}

SurveyTool/Views/SurveyCustomer/Create.cshtml
@model SurveyTool.Models.Survey

@{
    ViewBag.Title = Model.Name;
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
    int count = 0;
}

@section Scripts
{
    <script type="text/javascript">
        $(function () {
            $('.datepicker').datepicker({ format: 'mm/dd/yyyy' });

            $(document).on('click', 'a[data-toggle=comment]', function () {
                var id = $(this).attr('href');
                $(id).toggle();
                return false;
            });
        });
    </script>
}

<div class="page-header headerpage">
    <h1>@ViewBag.Title</h1>
    <div>
        <p style="color:red">* Bắt buộc</p>
    </div>
</div>

<form action="@Url.Action("CreateResponse", "SurveyCustomer", new {surveyId = Request["surveyId"]})" method="post" id="form_Response">


    @foreach (var question in Model.Questions)
    {
        <ul class="unstyled bordered skip-first">
            @{
                <li class="row question">
                    <div class="span9">
                        <input type="hidden" name="Answers.Index" value="@question.Id" />
                        <input type="hidden" name="Answers[@question.Id].QuestionId" value="@question.Id" />

                        @Html.Raw(question.Body)
                        @if (question.Required)
                        {
                            <span style="color:red">*</span>
                        }
                    </div>
                </li>
                <li class="row answer">
                    <div class="span12">
                        @if (question.Required)
                        {
                            if (question.Type == "Yes/No")
                            {
                                @*<select class="span3" name="Answers[@question.Id].Value">
                                        <option disabled selected>Chọn câu trả lời...</option>
                                        <option>Có</option>
                                        <option>Không</option>
                                    </select>*@
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Có" required
                                           oninvalid="this.setCustomValidity('Vui lòng trả lời câu hỏi')"
                                           oninput="setCustomValidity('')">

                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios[@count]">
                                        Có
                                    </label>

                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Không">
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios[@count]">
                                        Không
                                    </label>
                                </div>
                                count++;
                            }
                            if (question.Type == "Number")
                            {
                                <input class="span6" type="number" name="Answers[@question.Id].Value" placeholder="Nhập số..." required
                                       oninvalid="this.setCustomValidity('Vui lòng trả lời câu hỏi')"
                                       oninput="setCustomValidity('')" />
                            }
                            if (question.Type == "Correct/Incorrect")
                            {
                                <div class="form-check">
                                    <input class="form-check-input span6" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Có" required
                                           oninvalid="this.setCustomValidity('Vui lòng trả lời câu hỏi')"
                                           oninput="setCustomValidity('')">
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios2">
                                        Đúng
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input span6" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Không">
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios2">
                                        Sai
                                    </label>
                                </div>
                                count++;
                            }
                            if (question.Type == "Text")
                            {
                                <textarea class="span6" name="Answers[@question.Id].Value" placeholder="Nhập câu trả lời..." required
                                          oninvalid="this.setCustomValidity('Vui lòng trả lời câu hỏi')"
                                          oninput="setCustomValidity('')"></textarea>
                            }
                            if (question.Type == "Email")
                            {
                                <input class="form-check-input span6" type="email" name="Answers[@question.Id].Value" title="Nhập email của bạn" required="" placeholder="Nhập email của bạn..." oninvalid="if (this.value == ''){this.setCustomValidity('Vui lòng nhập email!')} if (this.value != ''){this.setCustomValidity('Email không hợp lệ!')}" oninput="setCustomValidity('')">
                            }
                        }
                        else
                        {
                            if (question.Type == "Yes/No")
                            {
                                @*<select class="span3" name="Answers[@question.Id].Value">
                                        <option disabled selected>Chọn câu trả lời...</option>
                                        <option>Có</option>
                                        <option>Không</option>
                                    </select>*@
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Có">
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios[@count]">
                                        Có
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Không">
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios[@count]">
                                        Không
                                    </label>
                                </div>
                                count++;
                            }
                            if (question.Type == "Number")
                            {
                                <input class="span6" type="number" name="Answers[@question.Id].Value" placeholder="Nhập số..." />
                            }
                            if (question.Type == "Correct/Incorrect")
                            {
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Có">
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios[@count]">
                                        Đúng
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Không">
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios[@count]">
                                        Sai
                                    </label>
                                </div>
                                count++;
                            }
                            if (question.Type == "Text")
                            {
                                <textarea class="span6" name="Answers[@question.Id].Value" placeholder="Nhập câu trả lời..."></textarea>
                            }
                            if (question.Type == "Email")
                            {
                                <input class="form-check-input span6" type="email" name="Answers[@question.Id].Value" placeholder="Nhập email của bạn..." required=""
                                       oninvalid="this.setCustomValidity('Email bắt buộc nhập')">
                            }
                        }

                        <div class="span12 commentsave">
                            <a href="@("#comment" + @question.Id)" data-toggle="comment"><small><i>Bình luận</i></small></a>
                        </div>
                        <div class="span12 commentsave">
                            <textarea id="@("comment" + question.Id)" class="span5 hide" name="Answers[@question.Id].Comment" placeholder="Để lại bình luận..."></textarea>
                        </div>
                    </div>
                </li>
            }
        </ul>

    }
    <div class="form-actions action">
        <input class="btn btn-primary" type="submit" name="action" value="Lưu" />
    </div>
</form>

SurveyTool/Views/SurveyCustomer/Details.cshtml
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

SurveyTool/Views/SurveyCustomer/Index.cshtml
@model SurveyTool.Models.Survey

@{
    ViewBag.Title = Model.Name;
    Layout = null;
    int count = 0;
}

@section Scripts
{
    <script type="text/javascript">
        $(function () {
            $('.datepicker').datepicker({ format: 'mm/dd/yyyy' });

            $(document).on('click', 'a[data-toggle=comment]', function () {
                var id = $(this).attr('href');
                $(id).toggle();
                return false;
            });
        });
    </script>
}

<div class="page-header headerpage">
    <h1>@ViewBag.Title</h1>
    <div>
        <p style="color:red">* Bắt buộc</p>
    </div>
</div>

<form action="@Url.Action("Create", "Statistic", new {surveyId = Request["surveyId"]})" method="post" id="form_Response">


    @foreach (var question in Model.Questions)
    {
        <ul class="unstyled bordered skip-first">
            @{
                <li class="row question">
                    <div class="span9">
                        <input type="hidden" name="Answers.Index" value="@question.Id" />
                        <input type="hidden" name="Answers[@question.Id].QuestionId" value="@question.Id" />

                        @Html.Raw(question.Body)
                        @if (question.Required)
                        {
                            <span style="color:red">*</span>
                        }
                    </div>
                </li>
                <li class="row answer">
                    <div class="span12">
                        @if (question.Required)
                        {
                            if (question.Type == "Yes/No")
                            {
                                @*<select class="span3" name="Answers[@question.Id].Value">
                                        <option disabled selected>Chọn câu trả lời...</option>
                                        <option>Có</option>
                                        <option>Không</option>
                                    </select>*@
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Có" required
                                           oninvalid="this.setCustomValidity('Vui lòng trả lời câu hỏi')"
                                           oninput="setCustomValidity('')">
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios[@count]">
                                        Có
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Không">
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios[@count]">
                                        Không
                                    </label>
                                </div>
                                count++;
                            }
                            if (question.Type == "Number")
                            {
                                <input class="span6" type="number" name="Answers[@question.Id].Value" placeholder="Nhập số..." required
                                       oninvalid="this.setCustomValidity('Vui lòng trả lời câu hỏi')"
                                       oninput="setCustomValidity('')" />
                            }
                            if (question.Type == "Correct/Incorrect")
                            {
                                <div class="form-check">
                                    <input class="form-check-input span6" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Có" required
                                           oninvalid="this.setCustomValidity('Vui lòng trả lời câu hỏi')"
                                           oninput="setCustomValidity('')">
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios2">
                                        Đúng
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input span6" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Không">
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios2">
                                        Sai
                                    </label>
                                </div>
                                count++;
                            }
                            if (question.Type == "Text")
                            {
                                <textarea name="Answers[@question.Id].Value" placeholder="Nhập câu trả lời..." required
                                          oninvalid="this.setCustomValidity('Vui lòng trả lời câu hỏi')"
                                          oninput="setCustomValidity('')"></textarea>
                            }
                            if (question.Type == "Email")
                            {
                                <input class="form-check-input" type="email" name="Answers[@question.Id].Value" title="Nhập email của bạn" required="" placeholder="Nhập email của bạn..." oninvalid="if (this.value == ''){this.setCustomValidity('Vui lòng nhập email!')} if (this.value != ''){this.setCustomValidity('Email không hợp lệ!')}" oninput="setCustomValidity('')">
                            }
                        }
                        else
                        {
                            if (question.Type == "Yes/No")
                            {
                                @*<select class="span3" name="Answers[@question.Id].Value">
                                        <option disabled selected>Chọn câu trả lời...</option>
                                        <option>Có</option>
                                        <option>Không</option>
                                    </select>*@
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Có">
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios[@count]">
                                        Có
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Không">
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios[@count]">
                                        Không
                                    </label>
                                </div>
                                count++;
                            }
                            if (question.Type == "Number")
                            {
                                <input class="span6" type="number" name="Answers[@question.Id].Value" placeholder="Nhập số..." />
                            }
                            if (question.Type == "Correct/Incorrect")
                            {
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Có">
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios[@count]">
                                        Đúng
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Không">
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios[@count]">
                                        Sai
                                    </label>
                                </div>
                                count++;
                            }
                            if (question.Type == "Text")
                            {
                                <textarea name="Answers[@question.Id].Value" placeholder="Nhập câu trả lời..."></textarea>
                            }
                            if (question.Type == "Email")
                            {
                                <input class="form-check-input" type="email" name="Answers[@question.Id].Value" placeholder="Nhập email của bạn..." required=""
                                       oninvalid="this.setCustomValidity('Email bắt buộc nhập')">
                            }
                        }

                        <div class="span12 commentsave">
                            <a href="@("#comment" + @question.Id)" data-toggle="comment"><small><i>Bình luận</i></small></a>
                        </div>
                        <div class="span12 commentsave">
                            <textarea id="@("comment" + question.Id)" class="span3 hide" name="Answers[@question.Id].Comment" placeholder="Để lại bình luận..."></textarea>
                        </div>
                    </div>
                </li>
            }
        </ul>

    }
    <div class="form-actions action">
        <button class="btn btn-warning pull-right" name="action" value="Next">
            Lưu và tiếp tục khảo sát khác
        </button>
        <input class="btn btn-primary" type="submit" name="action" value="Lưu" />
        <a class="btn btn-danger" href="@Url.Action("Index", "Home")">Hủy</a>
    </div>
</form>

SurveyTool/Views/SurveyCustomer/NotSubmitSurvey.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Not submit</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <style>
        body {
            background: rgb(240, 235, 248);
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row text-center">
            <div class="col-sm-6 col-sm-offset-3">
                <br><br> <h2 style="color:#0fad00">Xin lỗi</h2>
                <p style="font-size:20px;color:#5C5C5C;">
                    Bạn đã gửi quá số lần cho phép.
                </p>
                <br><br>
            </div>

        </div>
    </div>
</body>
</html>

SurveyTool/Views/SurveyCustomer/PageResponse.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Congurations</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <style>
        body{
            background:rgb(240, 235, 248);
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row text-center">
            <div class="col-sm-6 col-sm-offset-3">
                <br><br> <h2 style="color:#0fad00">Chúc mừng</h2>
                <p style="font-size:20px;color:#5C5C5C;">
                    Bài khảo sát đã được gửi.
                </p>
                <a href="http://localhost:36318/Surveys/@ViewBag.SurveyId/SurveyCustomer/Create">Gửi bài khảo sát khác</a>
                <br><br>
            </div>

        </div>
    </div>
</body>
</html>