SurveyTool/Controllers/ResponsesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SurveyTool.Models;

namespace SurveyTool.Controllers
{
    [Authorize]
    public class ResponsesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ResponsesController(ApplicationDbContext db)
        {
            _db = db;
        }

        [HttpGet]
        public ActionResult Index(int surveyId)
        {
            var userId = User.Identity.GetUserId();
            var responses = _db.Responses
                               .Include("Survey")
                               .Include("Answers")
                               .Include("Answers.Question")
                               .Where(x=>x.Survey.UserId.Equals(userId))
                               .Where(x => x.SurveyId == surveyId)
                               .Where(x => x.CreatedBy == User.Identity.Name)
                               .OrderByDescending(x => x.CreatedOn)
                               .ThenByDescending(x => x.Id)
                               .ToList();
            if (responses == null)
            {
                return Redirect("/pages/404");
            }
            return View(responses);
        }
        //Hiển thị lịch sử những lần khảo sát
        [HttpGet]
        public ActionResult Details(int surveyId, int id)
        {
            var response = _db.Responses
                              .Include("Survey")
                              .Include("Answers")
                              .Include("Answers.Question")
                              .Where(x => x.SurveyId == surveyId)
                              .Where(x => x.CreatedBy == User.Identity.Name)
                              .Single(x => x.Id == id);

            response.Answers = response.Answers.OrderBy(x => x.Question.Priority).ToList();
            if (response == null)
            {
                return Redirect("/pages/404");
            }
            return View(response);
        }

        [HttpGet]
        public ActionResult Create(int surveyId)
        {
            var survey = _db.Surveys
                            .Where(s => s.Id == surveyId)
                            .Select(s => new
                                {
                                    Survey = s,
                                    Questions = s.Questions
                                                 .Where(q => q.IsActive)
                                                 .OrderBy(q => q.Priority)
                                })
                             .AsEnumerable()
                             .Select(x =>
                                 {
                                     x.Survey.Questions = x.Questions.ToList();
                                     return x.Survey;
                                 })
                             .Single();
            if(survey==null)
            {
                return Redirect("/pages/404");
            }
            return View(survey);
        }

        [HttpPost]
        public ActionResult Create(int surveyId, string action, Response model)
        {
            model.Answers = model.Answers.Where(a => !String.IsNullOrEmpty(a.Value)).ToList();
            model.SurveyId = surveyId;
            model.CreatedBy = User.Identity.Name;
            model.CreatedOn = DateTime.Now;
            //Save infomation customer response
            var customer = new Customer();
            foreach(var item in model.Answers)
            {
                var question = _db.Questions.Where(x => x.Id == item.QuestionId).FirstOrDefault();
                if (question.Type.Equals("Email"))
                {
                    customer.Email = item.Value;
                    customer.Name = item.Value;
                }
            }
            _db.Customers.Add(customer);
            _db.SaveChanges();
            model.CusId = customer.Id;
            _db.Responses.Add(model);
            _db.SaveChanges();

            TempData["success"] = "Bài khảo sát đã được lưu!";

            return action == "Next"
                       ? RedirectToAction("Create", new {surveyId})
                       : RedirectToAction("Index", "Home");
        }

        public ActionResult Delete(int surveyId, int id, string returnTo)
        {
            var response = new Response() { Id = id, SurveyId = surveyId };
            _db.Entry(response).State = EntityState.Deleted;
            _db.SaveChanges();
            return Redirect(returnTo ?? Url.RouteUrl("Root"));
        }
    }
}

SurveyTool/Views/Responses/Create.cshtml
@model SurveyTool.Models.Survey

@{
    ViewBag.Title = Model.Name;
    int count = 0;
}

@section Scripts
{
    <script type="text/javascript">
        $(function () {
            $('.datepicker').datepicker({ format: 'mm/dd/yyyy' });

            $(document).on('click', 'a[data-toggle=comment]', function () {
                var id = $(this).attr('href');
                $(id).toggle();
                return false;
            });
        });
    </script>
}

<div class="page-header headerpage">
    <h1>@ViewBag.Title</h1>
    <div>
        <p style="color:red">* Bắt buộc</p>
    </div>
</div>

<form action="@Url.Action("Create", "Responses", new {surveyId = Request["surveyId"]})" method="post" id="form_Response">


    @foreach (var question in Model.Questions)
    {
        <ul class="unstyled bordered skip-first">
            @{
                <li class="row question">
                    <div class="span9">
                        <input type="hidden" name="Answers.Index" value="@question.Id" />
                        <input type="hidden" name="Answers[@question.Id].QuestionId" value="@question.Id" />

                        @Html.Raw(question.Body)
                        @if (question.Required)
                        {
                            <span style="color:red">*</span>
                        }
                    </div>
                </li>
                <li class="row answer">
                    <div class="span12">
                        @if (question.Required)
                        {
                            if (question.Type == "Yes/No")
                            {
                                @*<select class="span3" name="Answers[@question.Id].Value">
                    <option disabled selected>Chọn câu trả lời...</option>
                    <option>Có</option>
                    <option>Không</option>
                </select>*@
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Có" required
                                           oninvalid="this.setCustomValidity('Vui lòng trả lời câu hỏi')"
                                           oninput="setCustomValidity('')">
                                    
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios[@count]">
                                        Có
                                    </label>
                                    
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Không">
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios[@count]">
                                        Không
                                    </label>
                                </div>
                                count++;
                            }
                            if (question.Type == "Number")
                            {
                                <input class="span6" type="number" name="Answers[@question.Id].Value" placeholder="Nhập số..." required
                                       oninvalid="this.setCustomValidity('Vui lòng trả lời câu hỏi')"
                                       oninput="setCustomValidity('')" />
                            }
                            if (question.Type == "Correct/Incorrect")
                            {
                                <div class="form-check">
                                    <input class="form-check-input span6" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Có" required
                                           oninvalid="this.setCustomValidity('Vui lòng trả lời câu hỏi')"
                                           oninput="setCustomValidity('')">
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios2">
                                        Đúng
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input span6" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Không">
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios2">
                                        Sai
                                    </label>
                                </div>
                                count++;
                            }
                            if (question.Type == "Text")
                            {
                                <textarea class="span6" name="Answers[@question.Id].Value" placeholder="Nhập câu trả lời..." required
                                          oninvalid="this.setCustomValidity('Vui lòng trả lời câu hỏi')"
                                          oninput="setCustomValidity('')"></textarea>
                            }
                            if (question.Type == "Email")
                            {
                                <input class="form-check-input span6" type="email" name="Answers[@question.Id].Value" title="Nhập email của bạn" required="" placeholder="Nhập email của bạn..." oninvalid="if (this.value == ''){this.setCustomValidity('Vui lòng nhập email!')} if (this.value != ''){this.setCustomValidity('Email không hợp lệ!')}" oninput="setCustomValidity('')">
                            }
                        }
                        else
                        {
                            if (question.Type == "Yes/No")
                            {
                                @*<select class="span3" name="Answers[@question.Id].Value">
                    <option disabled selected>Chọn câu trả lời...</option>
                    <option>Có</option>
                    <option>Không</option>
                </select>*@
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Có">
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios[@count]">
                                        Có
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Không">
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios[@count]">
                                        Không
                                    </label>
                                </div>
                                count++;
                            }
                            if (question.Type == "Number")
                            {
                                <input class="span6" type="number" name="Answers[@question.Id].Value" placeholder="Nhập số..." />
                            }
                            if (question.Type == "Correct/Incorrect")
                            {
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Có">
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios[@count]">
                                        Đúng
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="Answers[@question.Id].Value" id="exampleRadios[@count]" value="Không">
                                    <label class="form-check-label" style="display:inline-block" for="exampleRadios[@count]">
                                        Sai
                                    </label>
                                </div>
                                count++;
                            }
                            if (question.Type == "Text")
                            {
                                <textarea class="span6" name="Answers[@question.Id].Value" placeholder="Nhập câu trả lời..."></textarea>
                            }
                            if (question.Type == "Email")
                            {
                                <input class="form-check-input span6" type="email" name="Answers[@question.Id].Value" placeholder="Nhập email của bạn..." required=""
                                       oninvalid="this.setCustomValidity('Email bắt buộc nhập')">
                            }
                        }

                        <div class="span12 commentsave">
                            <a href="@("#comment" + @question.Id)" data-toggle="comment"><small><i>Bình luận</i></small></a>
                        </div>
                        <div class="span12 commentsave">
                            <textarea id="@("comment" + question.Id)" class="span5 hide" name="Answers[@question.Id].Comment" placeholder="Để lại bình luận..."></textarea>
                        </div>
                    </div>
                </li>
            }
        </ul>

    }
    <div class="form-actions action">
        <button class="btn btn-warning pull-right" name="action" value="Next">
            Lưu và tiếp tục khảo sát khác
        </button>
        <input class="btn btn-primary" type="submit" name="action" value="Lưu" />
        <a class="btn btn-danger" href="@Url.Action("Index", "Home")">Hủy</a>
    </div>
</form>

SurveyTool/Views/Responses/Details.cshtml
@model SurveyTool.Models.Response

@{
    ViewBag.Title = Model.Survey.Name;
}

<div class="page-header">
    <h3>@ViewBag.Title</h3>
</div>

<div class="well well-small">
    <h4>Thông tin khảo sát</h4>
</div>
<ul class="unstyled bordered skip-first">
    <li class="row">
        <div class="span9">
            <label><b>Người tham gia khảo sát   </b></label>
            <p class="help-block">
                Đã hoàn thành bài khảo sát
            </p>
        </div>
        <div class="span3">
            <div class="well well-small">
                @Model.CreatedBy
            </div>
        </div>
    </li>
    <li class="row">
        <div class="span9">
            <label><b>Thời gian</b></label>
            <p class="help-block">
                Thời gian người này bắt đầu khảo sát
            </p>
        </div>
        <div class="span3">
            <div class="well well-small">
                @Model.CreatedOn.ToString("d")
            </div>
        </div>
    </li>
</ul>

<div class="well well-small">
    <h4>Câu hỏi</h4>
</div>
<ul class="unstyled bordered skip-first">
    @foreach (var item in Model.Answers)
    {
        <li class="row">
            <div class="span9">
                @Html.Raw(item.Question.Body)
            </div>
            <div class="span3">
                <div class="well well-small">@item.Value</div>
                <div class="well well-small">@item.Comment</div>
            </div>
        </li>
    }
</ul>

SurveyTool/Views/Responses/Index.cshtml
@model IEnumerable<SurveyTool.Models.Response>

@{
    ViewBag.Title = "Phản hồi";
}

@section scripts
{
    @Scripts.Render("~/bundles/models")

    <script type="text/javascript">
        $(function () {
            ko.applyBindings(new ResponseListModel(), $('#response-list')[0]);
        })
    </script>
}

<div class="page-header">
    <h2>Phản hồi <small>Quản lý phản hồi</small></h2>
</div>

<table id="response-list" class="table table-striped">
    <thead>
        <tr>
            <th class="span1">Ngày</th>
            <th class="span5">Khảo sát</th>
            <th class="span2">Nhóm thành viên</th>
            <th class="span2">Kết quả</th>
            <th class="span2">Hành động</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td><span class="muted">@item.CreatedOn</span></td>
                <td>
                    <a href="@Url.Action("Details", "Responses", new {surveyId = item.SurveyId, id = item.Id})">
                        @item.Survey.Name
                    </a>
                </td>
                <td>
                    @item.CreatedBy
                </td>
                <td>
                    @item.GetAnswerCount()/@item.Survey.Questions.Count() - 
                    @item.CalculateScore(item.Survey.Questions.Count()).ToString("P1")
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete",
                                     new { Controller = "Responses", surveyId = item.SurveyId, id = item.Id },
                                     new { @class = "text-error", data_bind = "click: destroy" })
                </td>
            </tr>
        }
    </tbody>
</table>